name: gsdatabase
description: Dart library to load and parse my custom gsdatabase
version: 1.0.7
# repository: https://github.com/exbraiin/dart-gsdatabase

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # dartx: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.3.0
  build_runner: ^2.4.7
